name: Frontend CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    # 1. Frontend 코드 체크아웃
    - name: Checkout Frontend Code
      uses: actions/checkout@v3

    # 2. 프론트엔드 코드 EC2로 동기화
    - name: Sync Frontend to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -aq --stats --human-readable \
          --exclude '.git/' \
          --exclude '.github/' \
          --exclude 'README.md' \
          --exclude '*.md' \
          --exclude '.idea/' \
          -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/ftt_frontend/

    # 3. EC2 서버에서 빌드 및 실행 (필요한 경우)
    - name: Build Frontend on EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          if [ -d "/home/ubuntu/ftt_frontend/" ]; then
            cd /home/ubuntu/ftt_frontend/
          else
            echo "Error: /home/ubuntu/ftt_frontend/ does not exist"
            exit 1
          fi
          npm install
          npm run build
